version: '3.2'

services:
  mofacts:
    container_name: mofacts
    restart: always
    image: iisdevs/mofacts-mini
    volumes:
      - type: bind
        source: /mofactsAssets
        target: /mofactsAssets
        bind:
          create_host_path: true
      - type: bind
        source: /dynamic-assets
        target: /dynamic-assets
        bind:
          create_host_path: true
      - type: bind
        source: /var/log/mofacts
        target: /mofactsAssets/logs
        bind:
          create_host_path: true
    logging:
      driver: json-file
      options:
        max-size: "10m"  # Optional, customize the maximum size of each log file (default 10m)
        max-file: "5"   # Optional, customize the maximum number of log files (default 5)
    ports:
      - '80:3000'
    depends_on:
      - mongodb
      - syllables
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongodb:27017/MoFaCT
      PORT: 3000
      SYLLABLES_URL: http://syllables:4567
      WAIT_HOSTS: mongo:27017 syllables:4567
      METEOR_SETTINGS_WORKAROUND: '/mofactsAssets/settings.json'
    networks:
      - mofacts

  mongodb:
    image: mongo:4.4.6
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - mofacts

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  syllables:
    image: iisdevs/mofacts-syllables
    ports:
      - '4567:4567'
    networks:
      - mofacts


volumes:
  mongodb:
    driver: local

networks:
  mofacts:
    driver: bridge